checkin for moving from asp.net mvc 3 to asp.net mvc 4
Moving single line in detail.cshtml addresses the following compilation error when the line is left where it is (issue with moving from Razor 1 to Razor 2?)

Compilation Error

Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.

Compiler Error Message: CS1513: } expected

Source Error:

Line 1849:        }
Line 1850:    }
Line 1851:}

Source File: c:\Users\ehtzrhf\AppData\Local\Temp\Temporary ASP.NET Files\root\9617aee5\55a8b9cc\App_Web_details.cshtml.ffd67fc0.4mlbitko.0.cs    Line: 1851